var s=`BTC/USD	5 знаков	8 знаков
BTC/EUR	5 знаков	8 знаков
BTC/RUR	5 знаков	8 знаков
LTC/BTC	8 знаков	8 знаков
LTC/USD	5 знаков	8 знаков
EMC/BTC	8 знаков	8 знаков
EMC/USD	5 знаков	8 знаков
EMC/RUR	5 знаков	8 знаков
EMC/ETH	8 знаков	8 знаков
EMC/DASH	8 знаков	8 знаков
EMC/XMR	8 знаков	8 знаков
DASH/BTC	8 знаков	8 знаков
DASH/USD	5 знаков	8 знаков
ETH/BTC	8 знаков	8 знаков
ETH/USD	5 знаков	8 знаков
ETH/RUR	5 знаков	8 знаков
MAID/BTC	8 знаков	8 знаков
DOGE/BTC	8 знаков	8 знаков
DOGE/USD	8 знаков	8 знаков
CURE/BTC	8 знаков	8 знаков
SIB/BTC	8 знаков	8 знаков
SIB/RUR	5 знаков	8 знаков
TX/BTC	8 знаков	8 знаков
RBIES/BTC	8 знаков	8 знаков
ADZ/BTC	8 знаков	8 знаков
ADZ/USD	5 знаков	8 знаков
BSD/BTC	8 знаков	8 знаков
SXC/BTC	8 знаков	8 знаков
BTA/BTC	8 знаков	8 знаков
VOX/BTC	8 знаков	8 знаков
MOJO/BTC	8 знаков	8 знаков
CRBIT/BTC	8 знаков	8 знаков
CRBIT/LEO	8 знаков	8 знаков
CRBIT/ETH	8 знаков	8 знаков
SHIFT/BTC	8 знаков	8 знаков
SHIFT/USD	5 знаков	8 знаков
SHIFT/ETH	8 знаков	8 знаков
YOC/BTC	8 знаков	8 знаков
YOC/USD	5 знаков	8 знаков
YOC/RUR	5 знаков	8 знаков
YOC/ETH	8 знаков	8 знаков
CREVA/BTC	8 знаков	8 знаков
LSK/BTC	8 знаков	8 знаков
LSK/USD	5 знаков	8 знаков
EL/BTC	8 знаков	8 знаков
EL/USD	5 знаков	8 знаков
EL/RUR	5 знаков	8 знаков
HNC/BTC	8 знаков	8 знаков
HNC/ETH	8 знаков	8 знаков
HNC/USD	5 знаков	8 знаков
HNC/EUR	5 знаков	8 знаков
CLOAK/BTC	8 знаков	8 знаков
CLOAK/USD	5 знаков	8 знаков
MOIN/BTC	8 знаков	8 знаков
BLU/BTC	8 знаков	8 знаков
BLU/USD	5 знаков	8 знаков
LEO/BTC	8 знаков	8 знаков
LEO/USD	5 знаков	8 знаков
LEO/RUR	5 знаков	8 знаков
LEO/ETH	8 знаков	8 знаков
PPC/BTC	8 знаков	8 знаков
PPC/USD	5 знаков	8 знаков
NMC/BTC	8 знаков	8 знаков
MONA/BTC	8 знаков	8 знаков
REE/BTC	8 знаков	8 знаков
REE/USD	5 знаков	8 знаков
REE/ETH	8 знаков	8 знаков
GAME/BTC	8 знаков	8 знаков
BLK/BTC	8 знаков	8 знаков
SYS/BTC	8 знаков	8 знаков
DGB/BTC	8 знаков	8 знаков
THS/BTC	8 знаков	8 знаков
THS/USD	5 знаков	8 знаков
THS/RUR	5 знаков	8 знаков
THS/ETH	8 знаков	8 знаков
VRC/BTC	8 знаков	8 знаков
SLR/BTC	8 знаков	8 знаков
DBIX/BTC	8 знаков	8 знаков
XMR/BTC	8 знаков	8 знаков
XMR/USD	5 знаков	8 знаков
BTS/BTC	8 знаков	8 знаков
GB/BTC	8 знаков	8 знаков
VRM/BTC	8 знаков	8 знаков
ATX/BTC	8 знаков	8 знаков
ENT/BTC	8 знаков	8 знаков
BURST/BTC	8 знаков	8 знаков
NXT/BTC	8 знаков	8 знаков
POST/BTC	8 знаков	8 знаков
POST/ETH	8 знаков	8 знаков
EDR/BTC	8 знаков	8 знаков
EDR/USD	5 знаков	8 знаков
EDR/RUR	5 знаков	8 знаков
KRB/BTC	8 знаков	8 знаков
KRB/USD	5 знаков	8 знаков
KRB/RUR	5 знаков	8 знаков
ARC/BTC	8 знаков	8 знаков
ARC/USD	5 знаков	8 знаков
ARC/RUR	5 знаков	8 знаков
ARC/ETH	8 знаков	8 знаков
ARC/BCH	8 знаков	8 знаков
GYC/BTC	8 знаков	8 знаков
DMC/BTC	8 знаков	8 знаков
DMC/USD	5 знаков	8 знаков
VRS/BTC	8 знаков	8 знаков
VRS/USD	5 знаков	8 знаков
XRC/BTC	8 знаков	8 знаков
XRC/USD	5 знаков	8 знаков
BIT/BTC	8 знаков	8 знаков
DOLLAR/BTC	8 знаков	8 знаков
OD/BTC	8 знаков	8 знаков
XAUR/BTC	8 знаков	8 знаков
GOLOS/BTC	8 знаков	8 знаков
FRST/BTC	8 знаков	8 знаков
FRST/USD	5 знаков	8 знаков
FRST/ETH	8 знаков	8 знаков
UNC/BTC	8 знаков	8 знаков
VLTC/BTC	8 знаков	8 знаков
CCRB/BTC	8 знаков	8 знаков
CCRB/ETH	8 знаков	8 знаков
BPC/BTC	8 знаков	8 знаков
BPC/ETH	8 знаков	8 знаков
EUR/USD	5 знаков	5 знаков
USD/RUR	5 знаков	5 знаков
PRES/BTC	8 знаков	8 знаков
DIME/BTC	8 знаков	8 знаков
DIME/USD	5 знаков	8 знаков
DIME/EUR	5 знаков	8 знаков
DIME/RUR	5 знаков	8 знаков
DIME/ETH	8 знаков	8 знаков
ZBC/BTC	8 знаков	8 знаков
ZBC/USD	5 знаков	8 знаков
ZBC/EUR	5 знаков	8 знаков
ZBC/RUR	5 знаков	8 знаков
ZBC/ETH	8 знаков	8 знаков
ZBC/XMR	8 знаков	8 знаков
ZBC/DANC	8 знаков	8 знаков
DIBC/BTC	8 знаков	8 знаков
DIBC/USD	5 знаков	8 знаков
DIBC/ETH	8 знаков	8 знаков
VSL/BTC	8 знаков	8 знаков
ICN/BTC	8 знаков	8 знаков
NVC/BTC	8 знаков	8 знаков
NVC/USD	5 знаков	8 знаков
XSPEC/BTC	8 знаков	8 знаков
ABN/BTC	8 знаков	8 знаков
BCC/BTC	8 знаков	8 знаков
BCC/USD	5 знаков	8 знаков
BCC/ETH	8 знаков	8 знаков
LUNA/BTC	8 знаков	8 знаков
ACN/BTC	8 знаков	8 знаков
LDC/BTC	8 знаков	8 знаков
MSCN/BTC	8 знаков	8 знаков
MSCN/USD	5 знаков	8 знаков
MSCN/EUR	5 знаков	8 знаков
MSCN/RUR	5 знаков	8 знаков
MSCN/ETH	8 знаков	8 знаков
POSW/BTC	8 знаков	8 знаков
POSW/USD	5 знаков	8 знаков
POSW/EUR	5 знаков	8 знаков
POSW/RUR	5 знаков	8 знаков
POSW/ETH	8 знаков	8 знаков
POSW/DASH	8 знаков	8 знаков
POSW/XMR	8 знаков	8 знаков
POSW/LTC	8 знаков	8 знаков
OBITS/BTC	8 знаков	8 знаков
OBITS/USD	5 знаков	8 знаков
OBITS/ETH	8 знаков	8 знаков
TIME/BTC	8 знаков	8 знаков
WAVES/BTC	8 знаков	8 знаков
DANC/BTC	8 знаков	8 знаков
DANC/USD	5 знаков	8 знаков
INCNT/BTC	8 знаков	8 знаков
TAAS/BTC	8 знаков	8 знаков
TAAS/USD	5 знаков	8 знаков
XMS/BTC	8 знаков	8 знаков
SOAR/BTC	8 знаков	8 знаков
SOAR/ETH	8 знаков	8 знаков
PIVX/BTC	8 знаков	8 знаков
PIVX/USD	5 знаков	8 знаков
PIVX/EUR	5 знаков	8 знаков
PIVX/RUR	5 знаков	8 знаков
PIVX/ETH	8 знаков	8 знаков
FUNC/BTC	8 знаков	8 знаков
FUNC/USD	5 знаков	8 знаков
FUNC/ETH	8 знаков	8 знаков
ITI/BTC	8 знаков	8 знаков
ITI/EUR	5 знаков	8 знаков
ITI/RUR	5 знаков	8 знаков
ITI/ETH	8 знаков	8 знаков
PUT/BTC	8 знаков	8 знаков
PUT/USD	5 знаков	8 знаков
PUT/RUR	5 знаков	8 знаков
PUT/ETH	8 знаков	8 знаков
GUP/BTC	8 знаков	8 знаков
GUP/ETH	8 знаков	8 знаков
MNE/BTC	8 знаков	8 знаков
MNE/ETH	8 знаков	8 знаков
WINGS/BTC	8 знаков	8 знаков
WINGS/ETH	8 знаков	8 знаков
UNRC/BTC	8 знаков	8 знаков
UNRC/USD	5 знаков	8 знаков
RLT/BTC	8 знаков	8 знаков
RLT/USD	5 знаков	8 знаков
RLT/RUR	5 знаков	8 знаков
RLT/ETH	8 знаков	8 знаков
FORTYTWO/BTC	8 знаков	8 знаков
FORTYTWO/USD	5 знаков	8 знаков
FORTYTWO/ETH	8 знаков	8 знаков
STRAT/BTC	8 знаков	8 знаков
STRAT/USD	5 знаков	8 знаков
STRAT/ETH	8 знаков	8 знаков
INSN/BTC	8 знаков	8 знаков
INSN/USD	5 знаков	8 знаков
INSN/ETH	8 знаков	8 знаков
QAU/BTC	8 знаков	8 знаков
QAU/USD	5 знаков	8 знаков
QAU/ETH	8 знаков	8 знаков
TRUMP/BTC	8 знаков	8 знаков
TRUMP/ETH	8 знаков	8 знаков
FNC/BTC	8 знаков	8 знаков
FNC/ETH	8 знаков	8 знаков
FNC/USD	5 знаков	8 знаков
MCO/BTC	8 знаков	8 знаков
MCO/USD	5 знаков	8 знаков
MCO/ETH	8 знаков	8 знаков
VOISE/BTC	8 знаков	8 знаков
VOISE/USD	5 знаков	8 знаков
VOISE/EUR	5 знаков	8 знаков
VOISE/ETH	8 знаков	8 знаков
PPY/BTC	8 знаков	8 знаков
PPY/USD	5 знаков	8 знаков
PPY/ETH	8 знаков	8 знаков
ASAFE2/BTC	8 знаков	8 знаков
ASAFE2/USD	5 знаков	8 знаков
PLBT/BTC	8 знаков	8 знаков
PLBT/EMC	8 знаков	8 знаков
PLBT/ETH	8 знаков	8 знаков
PLBT/USD	5 знаков	8 знаков
KPL/BTC	8 знаков	8 знаков
KPL/USD	5 знаков	8 знаков
KPL/ETH	8 знаков	8 знаков
BCH/BTC	8 знаков	8 знаков
BCH/USD	5 знаков	8 знаков
BCH/RUR	5 знаков	8 знаков
BCH/ETH	8 знаков	8 знаков
BCH/ZBC	8 знаков	8 знаков
MCR/BTC	8 знаков	8 знаков
MCR/ETH	8 знаков	8 знаков
PIPL/BTC	8 знаков	8 знаков
PIPL/ETH	8 знаков	8 знаков
HVN/BTC	8 знаков	8 знаков
HVN/USD	5 знаков	8 знаков
HVN/ETH	8 знаков	8 знаков
XRL/BTC	8 знаков	8 знаков
XRL/ETH	8 знаков	8 знаков
MGO/BTC	8 знаков	8 знаков
MGO/ETH	8 знаков	8 знаков
FU/BTC	8 знаков	8 знаков
FU/ETH	8 знаков	8 знаков
WIC/BTC	8 знаков	8 знаков
WIC/ETH	8 знаков	8 знаков
CTR/BTC	8 знаков	8 знаков
CTR/USD	5 знаков	8 знаков
CTR/ETH	8 знаков	8 знаков
GRS/BTC	8 знаков	8 знаков
GRS/USD	5 знаков	8 знаков
GRS/ETH	8 знаков	8 знаков
PRO/BTC	8 знаков	8 знаков
PRO/USD	5 знаков	8 знаков
PRO/ETH	8 знаков	8 знаков
XEM/BTC	8 знаков	8 знаков
XEM/USD	5 знаков	8 знаков
XEM/ETH	8 знаков	8 знаков
CPC/BTC	8 знаков	8 знаков
CPC/USD	5 знаков	8 знаков
CPC/ETH	8 знаков	8 знаков
wETT/BTC	8 знаков	8 знаков
wETT/USD	5 знаков	8 знаков
wETT/ETH	8 знаков	8 знаков
eETT/BTC	8 знаков	8 знаков
eETT/USD	5 знаков	8 знаков
eETT/ETH	8 знаков	8 знаков
SUMO/BTC	8 знаков	8 знаков
SUMO/ETH	8 знаков	8 знаков
QTUM/BTC	8 знаков	8 знаков
QTUM/USD	5 знаков	8 знаков
QTUM/ETH	8 знаков	8 знаков
OMG/BTC	8 знаков	8 знаков
OMG/USD	5 знаков	8 знаков
OMG/ETH	8 знаков	8 знаков
PAY/BTC	8 знаков	8 знаков
PAY/USD	5 знаков	8 знаков
PAY/ETH	8 знаков	8 знаков
KNC/BTC	8 знаков	8 знаков
KNC/USD	5 знаков	8 знаков
KNC/ETH	8 знаков	8 знаков
GNT/BTC	8 знаков	8 знаков
GNT/USD	5 знаков	8 знаков
GNT/ETH	8 знаков	8 знаков
EOS/BTC	8 знаков	8 знаков
EOS/USD	5 знаков	8 знаков
EOS/ETH	8 знаков	8 знаков
BAT/BTC	8 знаков	8 знаков
BAT/USD	5 знаков	8 знаков
BAT/ETH	8 знаков	8 знаков
REP/BTC	8 знаков	8 знаков
REP/USD	5 знаков	8 знаков
REP/ETH	8 знаков	8 знаков
MTL/BTC	8 знаков	8 знаков
MTL/USD	5 знаков	8 знаков
MTL/ETH	8 знаков	8 знаков
DGD/BTC	8 знаков	8 знаков
DGD/USD	5 знаков	8 знаков
DGD/ETH	8 знаков	8 знаков
CVC/BTC	8 знаков	8 знаков
CVC/USD	5 знаков	8 знаков
CVC/ETH	8 знаков	8 знаков
SNGLS/BTC	8 знаков	8 знаков
SNGLS/USD	5 знаков	8 знаков
SNGLS/ETH	8 знаков	8 знаков
SNT/BTC	8 знаков	8 знаков
SNT/USD	5 знаков	8 знаков
SNT/ETH	8 знаков	8 знаков
GNO/BTC	8 знаков	8 знаков
GNO/USD	5 знаков	8 знаков
GNO/ETH	8 знаков	8 знаков
ZRX/BTC	8 знаков	8 знаков
ZRX/USD	5 знаков	8 знаков
ZRX/ETH	8 знаков	8 знаков
BNT/BTC	8 знаков	8 знаков
BNT/USD	5 знаков	8 знаков
BNT/ETH	8 знаков	8 знаков
FUN/BTC	8 знаков	8 знаков
FUN/USD	5 знаков	8 знаков
FUN/ETH	8 знаков	8 знаков
EDG/BTC	8 знаков	8 знаков
EDG/USD	5 знаков	8 знаков
EDG/ETH	8 знаков	8 знаков
ANT/BTC	8 знаков	8 знаков
ANT/USD	5 знаков	8 знаков
ANT/ETH	8 знаков	8 знаков
ETHOS/BTC	8 знаков	8 знаков
ETHOS/USD	5 знаков	8 знаков
ETHOS/ETH	8 знаков	8 знаков
STORJ/BTC	8 знаков	8 знаков
STORJ/USD	5 знаков	8 знаков
STORJ/ETH	8 знаков	8 знаков
RLC/BTC	8 знаков	8 знаков
RLC/USD	5 знаков	8 знаков
RLC/ETH	8 знаков	8 знаков
TKN/BTC	8 знаков	8 знаков
TKN/USD	5 знаков	8 знаков
TKN/ETH	8 знаков	8 знаков
MLN/BTC	8 знаков	8 знаков
MLN/USD	5 знаков	8 знаков
MLN/ETH	8 знаков	8 знаков
TRST/BTC	8 знаков	8 знаков
TRST/USD	5 знаков	8 знаков
TRST/ETH	8 знаков	8 знаков
FirstBlood/BTC	8 знаков	8 знаков
FirstBlood/USD	5 знаков	8 знаков
FirstBlood/ETH	8 знаков	8 знаков
VIB/BTC	8 знаков	8 знаков
VIB/USD	5 знаков	8 знаков
VIB/ETH	8 знаков	8 знаков
MTCoin/BTC	8 знаков	8 знаков
MTCoin/ETH	8 знаков	8 знаков
BIO/BTC	8 знаков	8 знаков
BIO/ETH	8 знаков	8 знаков
BIO/RUR	5 знаков	8 знаков
BIO/USD	5 знаков	8 знаков
NEO/BTC	8 знаков	8 знаков
NEO/USD	5 знаков	8 знаков
NEO/ETH	8 знаков	8 знаков
OTN/BTC	8 знаков	8 знаков
OTN/USD	5 знаков	8 знаков
OTN/ETH	8 знаков	8 знаков
MNX/BTC	8 знаков	8 знаков
MNX/USD	5 знаков	8 знаков
MNX/ETH	8 знаков	8 знаков
ENJ/BTC	8 знаков	8 знаков
ENJ/ETH	8 знаков	8 знаков
DAY/BTC	8 знаков	8 знаков
DAY/ETH	8 знаков	8 знаков
ETHP/BTC	8 знаков	8 знаков
ETHP/ETH	8 знаков	8 знаков
ATM/BTC	8 знаков	8 знаков
ATM/ETH	8 знаков	8 знаков
DMD/BTC	8 знаков	8 знаков
DMD/USD	5 знаков	8 знаков
DMD/ETH	8 знаков	8 знаков
OXY/BTC	8 знаков	8 знаков
OXY/USD	5 знаков	8 знаков
OXY/ETH	8 знаков	8 знаков
CLD/BTC	8 знаков	8 знаков
CLD/ETH	8 знаков	8 знаков
ARTE/BTC	8 знаков	8 знаков
ARTE/ETH	8 знаков	8 знаков
CDX/BTC	8 знаков	8 знаков
CDX/ETH	8 знаков	8 знаков
CLPC/BTC	8 знаков	8 знаков
CLPC/USD	5 знаков	8 знаков
CLPC/ETH	8 знаков	8 знаков
ESP/BTC	8 знаков	8 знаков
ESP/ETH	8 знаков	8 знаков
BTB/BTC	8 знаков	8 знаков
BTB/ETH	8 знаков	8 знаков
ESC/BTC	8 знаков	8 знаков
ESC/ETH	8 знаков	8 знаков
PRG/BTC	8 знаков	8 знаков
PRG/USD	5 знаков	8 знаков
PRG/ETH	8 знаков	8 знаков
AMM/BTC	8 знаков	8 знаков
AMM/USD	5 знаков	8 знаков
AMM/ETH	8 знаков	8 знаков
HST/BTC	8 знаков	8 знаков
HST/USD	5 знаков	8 знаков
HST/ETH	8 знаков	8 знаков
ERO/BTC	8 знаков	8 знаков
ERO/ETH	8 знаков	8 знаков
KICK/BTC	8 знаков	8 знаков
KICK/USD	5 знаков	8 знаков
KICK/RUR	5 знаков	8 знаков
KICK/ETH	8 знаков	8 знаков
UQC/BTC	8 знаков	8 знаков
UQC/USD	5 знаков	8 знаков
UQC/ETH	8 знаков	8 знаков
UQC/BCC	8 знаков	8 знаков
GRX/BTC	8 знаков	8 знаков
GRX/ETH	8 знаков	8 знаков
INS/BTC	8 знаков	8 знаков
INS/ETH	8 знаков	8 знаков
ICOS/BTC	8 знаков	8 знаков
ICOS/USD	5 знаков	8 знаков
ICOS/ETH	8 знаков	8 знаков
TER/BTC	8 знаков	8 знаков
TER/ETH	8 знаков	8 знаков
FLP/BTC	8 знаков	8 знаков
FLP/ETH	8 знаков	8 знаков
RBM/BTC	8 знаков	8 знаков
RBM/USD	5 знаков	8 знаков
RBM/EUR	5 знаков	8 знаков
RBM/ETH	8 знаков	8 знаков
RBM/LTC	8 знаков	8 знаков
FLIXX/BTC	8 знаков	8 знаков
FLIXX/ETH	8 знаков	8 знаков
DTR/BTC	8 знаков	8 знаков
DTR/ETH	8 знаков	8 знаков
EVC/BTC	8 знаков	8 знаков
EVC/ETH	8 знаков	8 знаков
SPF/BTC	8 знаков	8 знаков
SPF/ETH	8 знаков	8 знаков
B2B/BTC	8 знаков	8 знаков
B2B/ETH	8 знаков	8 знаков
TFL/BTC	8 знаков	8 знаков
TFL/ETH	8 знаков	8 знаков
CHSB/BTC	8 знаков	8 знаков
CHSB/ETH	8 знаков	8 знаков
PIN/BTC	8 знаков	8 знаков
PIN/ETH	8 знаков	8 знаков
GOAL/BTC	8 знаков	8 знаков
GOAL/ETH	8 знаков	8 знаков
GOAL/USD	5 знаков	8 знаков
COV/BTC	8 знаков	8 знаков
COV/ETH	8 знаков	8 знаков
IFAN/BTC	8 знаков	8 знаков
IFAN/ETH	8 знаков	8 знаков
IPL/BTC	8 знаков	8 знаков
IPL/ETH	8 знаков	8 знаков
NOX/BTC	8 знаков	8 знаков
NOX/ETH	8 знаков	8 знаков
TWC/BTC	8 знаков	8 знаков
TWC/TER	8 знаков	8 знаков
TWC/ETH	8 знаков	8 знаков
KAPU/BTC	8 знаков	8 знаков
KAPU/ETH	8 знаков	8 знаков
TRX/BTC	8 знаков	8 знаков
TRX/ETH	8 знаков	8 знаков
TRX/USD	5 знаков	8 знаков
CRC/BTC	8 знаков	8 знаков
CRC/ETH	8 знаков	8 знаков
CRC/USD	5 знаков	8 знаков
CRC/EUR	5 знаков	8 знаков
ESR/BTC	8 знаков	8 знаков
ESR/ETH	8 знаков	8 знаков
ESR/BCH	8 знаков	8 знаков
ESR/DASH	8 знаков	8 знаков
IPBC/BTC	8 знаков	8 знаков
IPBC/ETH	8 знаков	8 знаков
IPBC/USD	5 знаков	8 знаков
IPBC/XMR	8 знаков	8 знаков
SPA/BTC	8 знаков	8 знаков
SPA/ETH	8 знаков	8 знаков
LTT/BTC	8 знаков	8 знаков
LTT/ETH	8 знаков	8 знаков
AMB/BTC	8 знаков	8 знаков
AMB/ETH	8 знаков	8 знаков
AMB/USD	5 знаков	8 знаков
AMB/RUR	5 знаков	8 знаков
ECHO/BTC	8 знаков	8 знаков
ECHO/ETH	8 знаков	8 знаков
ECHO/USD	5 знаков	8 знаков
HNR/BTC	8 знаков	8 знаков
HNR/ETH	8 знаков	8 знаков
HNR/USD	5 знаков	8 знаков
NAM/BTC	8 знаков	8 знаков
NAM/ETH	8 знаков	8 знаков
NAM/USD	5 знаков	8 знаков
ORE/BTC	8 знаков	8 знаков
ORE/ETH	8 знаков	8 знаков
ORE/USD	5 знаков	8 знаков
PPT/BTC	8 знаков	8 знаков
PPT/ETH	8 знаков	8 знаков
PPT/USD	5 знаков	8 знаков
VEN/BTC	8 знаков	8 знаков
VEN/ETH	8 знаков	8 знаков
VEN/USD	5 знаков	8 знаков
DIG/BTC	8 знаков	8 знаков
DIG/ETH	8 знаков	8 знаков
DIG/USD	5 знаков	8 знаков
DIG/LTC	8 знаков	8 знаков`;




String.prototype.replaceAll = function(search, replace){
    return this.split(search).join(replace);
  }



s=s.replaceAll("\n", "},\n{\"");
s=s.replaceAll("\t", "|");
s=s.replaceAll("знаков|", ", quantity:");       
s=s.replaceAll("знаков", "");   
s=s.replaceAll("|", "\", price:");     
s=s.replaceAll("{\"", "{market:\"");     
console.log(s);