module.exports.vertexes=[
    {
        "currency_local": 'USD',
        "currency_common": 'USD',
        "exchange": "livecoin",
        "transaction_amount": 3,
        "use_as_bridge_between_exchanges": false,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'DASH',
        "currency_common": 'DASH',
        "exchange": "livecoin",
        "transaction_amount": 0.01,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'BTC',
        "currency_common": 'BTC',
        "exchange": "livecoin",
        "transaction_amount": 0.0002,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.001,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'ETH',
        "currency_common": 'ETH',
        "exchange": "livecoin",
        "transaction_amount": 0.007,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.01,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'LTC',
        "currency_common": 'LTC',
        "exchange": "livecoin",
        "transaction_amount": 3,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.02,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'LSK',
        "currency_common": 'LSK',
        "exchange": "livecoin",
        "transaction_amount": 0.2,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.2,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'NEO',
        "currency_common": 'NEO',
        "exchange": "livecoin",
        "transaction_amount": 0.2,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'BCH',
        "currency_common": 'BCH',
        "exchange": "livecoin",
        "transaction_amount": 0.004,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.001,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'XMR',
        "currency_common": 'XMR',
        "exchange": "livecoin",
        "transaction_amount": 0.01,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.001,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'QTUM',
        "currency_common": 'QTUM',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.01,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'BTS',
        "currency_common": 'BTS',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 5,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'ICN',
        "currency_common": 'ICN',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 1,
        "output_percent_comission": 0, "description":""
    },
        {
        "currency_local": 'PIVX',
        "currency_common": 'PIVX',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.001,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'STRAT',
        "currency_common": 'STRAT',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.001,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'MCO',
        "currency_common": 'MCO',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.8,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'CTR',
        "currency_common": 'CTR',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 5,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'VIB',
        "currency_common": 'VIB',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 25,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'OMG',
        "currency_common": 'OMG',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.5,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'EOS',
        "currency_common": 'EOS',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.8,
        "output_percent_comission": 0, "description":""
    }
    ,
    {
        "currency_local": 'BAT',
        "currency_common": 'BAT',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 14,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'MTL',
        "currency_common": 'MTL',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 1,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'DGD',
        "currency_common": 'DGD',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.06,
        "output_percent_comission": 0, "description":""
    }
    ,
    {
        "currency_local": 'SNGLS',
        "currency_common": 'SNGLS',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 38,
        "output_percent_comission": 0, "description":""
    }
    ,
    {
        "currency_local": 'SNT',
        "currency_common": 'SNT',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 51,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'ZRX',
        "currency_common": 'ZRX',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 5,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'BNT',
        "currency_common": 'BNT',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 2,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'FUN',
        "currency_common": 'FUN',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 77,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'ETHOS',
        "currency_common": 'ETHOS',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 1.1,
        "output_percent_comission": 0, "description":""
    },
    {
        "currency_local": 'STORJ',
        "currency_common": 'STORJ',
        "exchange": "livecoin",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 5,
        "output_percent_comission": 0, "description":""
    }
]