module.exports.vertexes=[
    {
        "currency_local": 'BNB',
        "currency_common": 'BNB',
        "exchange": "binance",
        "transaction_amount": 8,
        "use_as_bridge_between_exchanges": false,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'USDT',
        "currency_common": 'USD',
        "exchange": "binance",
        "transaction_amount": 3,
        "use_as_bridge_between_exchanges": false,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'DASH',
        "currency_common": 'DASH',
        "exchange": "binance",
        "transaction_amount": 0.01,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.002,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'BTC',
        "currency_common": 'BTC',
        "exchange": "binance", 
        "transaction_amount": 0.0002,
        "use_as_bridge_between_exchanges": true,  
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.001,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'ETH',
        "currency_common": 'ETH',
        "exchange": "binance",
        "transaction_amount": 0.007,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.01,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'LTC',
        "currency_common": 'LTC',
        "exchange": "binance",
        "transaction_amount": 3,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.01,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'LSK',
        "currency_common": 'LSK',
        "exchange": "binance",
        "transaction_amount": 0.2,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.1,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'NEO',
        "currency_common": 'NEO',
        "exchange": "binance",
        "transaction_amount": 0.2,
        "use_as_bridge_between_exchanges": true,  
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'BCC',
        "currency_common": 'BCH',
        "exchange": "binance",
        "transaction_amount": 0.004,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.001,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'XMR',
        "currency_common": 'XMR',
        "exchange": "binance",
        "transaction_amount": 0.01,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.04,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'QTUM',
        "currency_common": 'QTUM',
        "exchange": "binance", 
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true, 
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0,
        "output_max": 0,
        "output_fixed_comission": 0.01,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'BTS',
        "currency_common": 'BTS',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 50,
        "output_max": 0,
        "output_fixed_comission": 1,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'ICN',
        "currency_common": 'ICN',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,  
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 4,
        "output_max": 0,
        "output_fixed_comission": 4.5,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'WAVES',
        "currency_common": 'WAVES',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0.1,
        "output_max": 0,
        "output_fixed_comission": 0.002,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'PIVX',
        "currency_common": 'PIVX',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0.1,
        "output_max": 0,
        "output_fixed_comission": 0.02,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'STRAT',
        "currency_common": 'STRAT',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0.002,
        "output_max": 0,
        "output_fixed_comission": 0.1,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'MCO',
        "currency_common": 'MCO',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0.6,
        "output_max": 0,
        "output_fixed_comission": 0.87,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'CTR',
        "currency_common": 'CTR',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 14,
        "output_max": 0,
        "output_fixed_comission": 6,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'VIB',
        "currency_common": 'VIB',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 40,
        "output_max": 0,
        "output_fixed_comission": 32,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'OMG',
        "currency_common": 'OMG',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0.6,
        "output_max": 0,
        "output_fixed_comission": 0.64,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'EOS',
        "currency_common": 'EOS',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 1.4,
        "output_max": 0,
        "output_fixed_comission": 0.8,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'BAT',
        "currency_common": 'BAT',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 30,
        "output_max": 0,
        "output_fixed_comission": 20,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'MTL',
        "currency_common": 'MTL',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 1,
        "output_max": 0,
        "output_fixed_comission": 2,
        "output_percent_comission": 0,  "decription":""
    }
    ,
    {
        "currency_local": 'DGD',
        "currency_common": 'DGD',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 0.06,
        "output_max": 0,
        "output_fixed_comission": 0.06,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'SNGLS',
        "currency_common": 'SNGLS',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 40,
        "output_max": 0,
        "output_fixed_comission": 39,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'SNT',
        "currency_common": 'SNT',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 20,
        "output_max": 0,
        "output_fixed_comission": 36,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'ZRX',
        "currency_common": 'ZRX',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 20,
        "output_max": 0,
        "output_fixed_comission": 6.3,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'BNT',
        "currency_common": 'BNT',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 2.4,
        "output_max": 0,
        "output_fixed_comission": 1.5,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'FUN',
        "currency_common": 'FUN',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 160,
        "output_max": 0,
        "output_fixed_comission": 103,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'BQX',
        "currency_common": 'ETHOS',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 4,
        "output_max": 0,
        "output_fixed_comission": 1.8,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'STORJ',
        "currency_common": 'STORJ',
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 6,
        "output_max": 0,
        "output_fixed_comission": 6.4,
        "output_percent_comission": 0,  "decription":""
    },
    {
        "currency_local": 'CMT',  
        "currency_common": 'CMT',  
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 30,
        "output_max": 0,
        "output_fixed_comission": 40,
        "output_percent_comission": 0,  "decription":"CyberMiles"
    },
    {
        "currency_local": 'TRX',  
        "currency_common": 'TRX', 
        "exchange": "binance",
        "transaction_amount": 5,
        "use_as_bridge_between_exchanges": true,
        "input_min": 0,
        "input_max": 0,
        "input_fixed_comission": 0,
        "input_percent_comission": 0,
        "output_min": 30,
        "output_max": 0,
        "output_fixed_comission": 40,
        "output_percent_comission": 0,  "decription":""
    },
        {
            "currency_local": 'XRP',  
            "currency_common": 'XRP',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'VEN',  
            "currency_common": 'VEN',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'WTC',  
            "currency_common": 'WTC',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'NANO',  
            "currency_common": 'NANO',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'ADA',  
            "currency_common": 'ADA',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'XLM',  
            "currency_common": 'XLM',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'NCASH',  
            "currency_common": 'NCASH',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'NULS',  
            "currency_common": 'NULS',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'POA',  
            "currency_common": 'POA',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'GXS',  
            "currency_common": 'GXS',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'SNT',  
            "currency_common": 'SNT',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'BCC',  
            "currency_common": 'BCC',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'CND',  
            "currency_common": 'CND',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        },
        {
            "currency_local": 'QSP',  
            "currency_common": 'QSP',  
            "exchange": "binance",
            "transaction_amount": 5,
            "use_as_bridge_between_exchanges": true,
            "input_min": 0,
            "input_max": 0,
            "input_fixed_comission": 0,
            "input_percent_comission": 0,
            "output_min": 30,
            "output_max": 0,
            "output_fixed_comission": 40,
            "output_percent_comission": 0,  "decription":""
        }
];